### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by xieruopeng** [pufengdu/PseAAC-General#1]
我的系统是ubuntu16.04，按照要求已经编译成功，以下是我成功make和make install打印的信息：
make[1]: Entering directory '/root/xieruopeng/feature/PseAAC-General-master/pseb'
g++ -I/root/xieruopeng/feature/PseAAC-General-master/lua-5.3.5/src -O3 -s -c bems.cpp 
g++ -I/root/xieruopeng/feature/PseAAC-General-master/lua-5.3.5/src -O3 -s -c biofiles.cpp
g++ -I/root/xieruopeng/feature/PseAAC-General-master/lua-5.3.5/src -O3 -s -c error.cpp 
g++ -I/root/xieruopeng/feature/PseAAC-General-master/lua-5.3.5/src -O3 -s -c fasta.cpp
g++ -I/root/xieruopeng/feature/PseAAC-General-master/lua-5.3.5/src -O3 -s -c luavm.cpp
g++ -I/root/xieruopeng/feature/PseAAC-General-master/lua-5.3.5/src -O3 -s -c parameters.cpp
g++ -I/root/xieruopeng/feature/PseAAC-General-master/lua-5.3.5/src -O3 -s -c pcprop.cpp
g++ -I/root/xieruopeng/feature/PseAAC-General-master/lua-5.3.5/src -O3 -s -c pseaac.cpp
g++ -I/root/xieruopeng/feature/PseAAC-General-master/lua-5.3.5/src -O3 -s -c pseb.cpp
g++ -I/root/xieruopeng/feature/PseAAC-General-master/lua-5.3.5/src -O3 -s -c tools.cpp
g++ -L/root/xieruopeng/feature/PseAAC-General-master/lua-5.3.5/src -o pseb bems.o biofiles.o error.o fasta.o luavm.o parameters.o pcprop.o pseaac.o pseb.o tools.o -dn -lz -lm -dy -llua -ldl
make[1]: Leaving directory '/root/xieruopeng/feature/PseAAC-General-master/pseb'
make[1]: Entering directory '/root/xieruopeng/feature/PseAAC-General-master/bmv'
g++ -I../pseb -s -O3 -c bmv.cpp -o bmv.o
g++ -I../pseb -s -O3 -c binmodview.cpp -o binmodview.o
g++ -I../pseb -s -O3 -o bmv bmv.o binmodview.o -lz -lm -static
make[1]: Leaving directory '/root/xieruopeng/feature/PseAAC-General-master/bmv'
make[1]: Entering directory '/root/xieruopeng/feature/PseAAC-General-master/bmc'
g++ -w -s -O3 -c bmc.cpp -o bmc.o
g++ -w -s -O3 -c listparser.cpp -o listparser.o
g++ -w -s -O3 -c ../pseb/tools.cpp -o tools.o
g++ -w -s -O3 -o bmc bmc.o listparser.o tools.o -lm -lz -static
make[1]: Leaving directory '/root/xieruopeng/feature/PseAAC-General-master/bmc'

make[1]: Entering directory '/root/xieruopeng/feature/PseAAC-General-master/pseb'
make[1]: 'pseb' is up to date.
make[1]: Leaving directory '/root/xieruopeng/feature/PseAAC-General-master/pseb'
make[1]: Entering directory '/root/xieruopeng/feature/PseAAC-General-master/bmv'
make[1]: 'bmv' is up to date.
make[1]: Leaving directory '/root/xieruopeng/feature/PseAAC-General-master/bmv'
make[1]: Entering directory '/root/xieruopeng/feature/PseAAC-General-master/bmc'
make[1]: 'bmc' is up to date.
make[1]: Leaving directory '/root/xieruopeng/feature/PseAAC-General-master/bmc'

编译成功后运行./pseb --usage   也是正常：
Usage: pseb [-adq?V] [-b BEM_FILE] [-e LUA_FILE] [-i INPUT_FILE] [-l LAMBDA]
            [-m {svm|csv|tab}] [-n VAR_STRING] [-o OUTPUT_FILE] [-s SEG]
            [-t PSE_TYPE] [-w WEIGHT] [-x SELECTION_FILE] [--aminoacid]
            [--bem-file=BEM_FILE] [--dipeptide] [--user-ext=LUA_FILE]
            [--input=INPUT_FILE] [--lambda=LAMBDA]
            [--output-format={svm|csv|tab}] [--ext-options=VAR_STRING]
            [--output=OUTPUT_FILE] [--query] [--segment=SEG] [--type=PSE_TYPE]
            [--weight=WEIGHT] [--select-aaindex=SELECTION_FILE] [--help]
            [--usage] [--version]

但是我按照论文中提供的指令./pseb -i test_pro.fasta -t 2 -b uniprot-go-05012013.bem，运行出现Segmentation fault (core dumped) 错误，并生成一个二进制core文件

**Comment by pufengdu** [comment]
Please note that the format of your test_pro.fasta must follow the restrictions.

-i, --input=INPUT_FILE     INPUT_FILE should be a valid fasta formated file.
                             The additional restriction is in the annotation
                             lines, which was always started by ">". Every
                             annotation line in the input fasta file must
                             contain two and only two fields, which are
                             seperated by "|". The first field is the id of the
                             sequences, which can be gi numbers, uniprot id,
                             accession numbers or anything t hat can identify
                             the sequence uniquely in the fasta file. The
                             second field is an integer, which is recognized as
                             the class label when you export the result. If you
                             do not need a class label, simply put a "0" in
                             this field. If you do not specify the
                             input_file_name, please omit the -i option
                             completely. In this case, the STDIN will be used
                             as the  input file.
